#!/usr/bin/env bash
#  ╦ ╦╦╔╦╗╔═╗  ╔╗ ╔═╗╦═╗
#  ╠═╣║ ║║║╣   ╠╩╗╠═╣╠╦╝
#  ╩ ╩╩═╩╝╚═╝  ╚═╝╩ ╩╩╚═
#	Simple script to hide/show polybar
#   Author: z0mbi3
#	url: https://github.com/gh0stzk

function hide() {
polybar-msg cmd hide | bspc config bottom_padding 2
}

function unhide() {
polybar-msg cmd show | bspc config bottom_padding 42
}

case $1 in
	-h | --hide | hide)
		hide
		exit;;
	-u | --unhide | unhide)
		unhide
		exit;;
	*) # Invalid option
		echo "Error: Invalid option"
		exit;;
esac
